version: '1'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.30
    ports:
      - "5775:5775"
      - "6831:6831/udp" # UDP
      - "6832:6832/udp" # UDP
      - "5778:5778"     # HTTP
      - "14268:14268"   # Collector HTTP
      - "14250:14250"   # Thrift over HTTP
      - "16686:16686"   # Jaeger UI
      - "16687:16687"   # Jaeger agent
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SiloPort=6000
      - DashboardPort=7000
      - ConnectionString=Server=database;Port=3306;Database=sandbox;Uid=root;Password=1234
      - ASPNETCORE_HTTP_PORTS=80
      - JaegerHost=jaeger
      - JaegerPort=6831
    ports:
      - 5000:80
      - 6000:6000
      - 7000:7000
    depends_on:
      - database
  database:
    image: mysql:8.0
    command: --sql_require_primary_key=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sandbox
      MYSQL_USER: local
      MYSQL_PASSWORD: 12345
    ports:
      - 3306:3306